language: java
version: ~> 1.0
os: linux
arch: arm64-graviton2
group: edge

branches:
  only:
  - master
  - dev
  
before_script:
  - sudo apt-get install ant-optional
  - git clone --branch=master https://github.com/Ludeme/TravisTrials.git ../TravisTrials
  
script:
  - cd PlayerDesktop
  - travis_wait 30 ant clean test
  
after_failure:
  - cat ./hs_err.log
  - cat ./replay.log